blog/urls.py
from django.urls import path
from .views import HomeView, PostView, CreatePostView, like_post, AboutView
from blog import views



urlpatterns = [
    path('', HomeView.as_view(), name = 'bloghome'),
    path('about/', AboutView.as_view(), name = 'about'),
    path('post/<int:pk>/', PostView.as_view(), name = 'blogdetail'),
    path('create_post/', CreatePostView.as_view(success_url='/'), name = 'createpost'),
    path('like/', views.like_post, name="like_post"),
    
]

coronastory/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from blog import views

from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('users/', include('users.urls')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('register/', views.register, name = 'register'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout')
]

blog/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils.text import slugify

# Create your models here.

class Post(models.Model):
    title = models.CharField(max_length=255)
 #   slug = models.SlugField(unique=True, blank=True)
    text = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    picture = models.ImageField(upload_to='pictures/%Y/%m/', max_length=255, null=True, blank=True)
    likes = models.ManyToManyField(User, related_name='likes', blank=True)
  
    def __str__(self):
        return f'{self.title}'


    def total_likes(self):
        return self.likes.count()


    # def get_absolute_url(self):
    #     return reverse("blog:post_detail", args=[self.id, self.slug])

users/models.py
from django.db import models

# Create your models here.

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class RegistrationForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email','password1','password2']

blog/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView, CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import RedirectView
from django.shortcuts import get_list_or_404, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.template.loader import render_to_string
from .models import Post

# Create your views here.

class HomeView(ListView):
    model = Post
    template_name = 'blog/index.html'
    context_object_name = "blog_posts"
    ordering =['-date']
    paginate_by = 6

class AboutView(ListView):
    model = Post
    template_name = 'blog/about.html'


class PostView(LoginRequiredMixin, DetailView):
    model = Post
    template_name = 'blog/post_detail.html'


class CreatePostView(LoginRequiredMixin, CreateView):
    model = Post
    template_name = 'blog/create_post.html'
    fields = ['title', 'text']

    def form_valid(self,form):
        form.instance.author = self.request.user
        return super().form_valid(form)

def like_post(request):
    # post = get_object_or_404(Post, id=request.POST.get('post_id'))
    post = get_object_or_404(Post, id=request.POST.get('id'))
    is_liked = False
    if post.likes.filter(id=request.user.id).exists():
        post.likes.remove(request.user)
        is_liked = False
    else:
        post.likes.add(request.user)
        is_liked = True
    context = {
        'post': post,
        'is_liked': is_liked,
        'total_likes': post.total_likes(),
    }
    if request.is_ajax():
        html = render_to_string('blog/like_section.html', context, request=request)
        return JsonResponse({'form': html})

users/views.py
from django.shortcuts import render, redirect
from .forms import RegistrationForm
from django.contrib.auth import authenticate, login

from django.contrib import messages

# Create your views here.

def register(request):
    if request.method =='POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Account is created')
            username = request.POST['username']
            password = request.POST['password1']
            user = authenticate(request, username=username, password=password)
            login(request, user)
            return redirect('login')
    else:
        form = RegistrationForm()

    context = {'form':form}

    return render(request, 'users/register.html', context)

blog/templates/blog/about.html
{% extends "blog/base.html" %}
{% block content %}
<div class="col-md-12">
 <div class="card mb-4">
 <div class="card-body">
  <h5 class="m-0 text-center"><b>Covid Stories</b></h5>
  <p>This blog is created to share your Covid survival and Fun stories on your lock down days. Share your stories anonymously, Keep it clean and post which are not relevant will be removed. Let's share and keep it going.</p>
</div>
</div>
</div>
{% endblock %}

blog/templates/blog/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Blog Home - CovidStories</title>

  

  <!-- Bootstrap core CSS -->
  <link href="{% static '/blog/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="{% static '/blog/css/blog-home.css' %}" rel="stylesheet">
  <link rel="icon" href="https://img.icons8.com/nolan/64/coronavirus.png" type="image/gif" sizes="16x16">

</head>

<body>

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
      <a class="navbar-brand" href="{% url 'bloghome' %}"><img src="https://img.icons8.com/nolan/32/coronavirus.png"><b>&nbsp Survival Stories</b></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'createpost' %}"><b>Submit Story</b></a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="{% url 'about' %}"><b>About</b></a>
          </li>
          </ul>
      </div>
    </div>
  </nav>

  <!-- Page Content -->
  <div class="container">

    <div class="row">
    
       {% block content %} {% endblock %}

    </div>

  </div>

        <!-- Footer -->
  <footer class="py-10 bg-dark">
    <div class="container">
      <p class="m-0 text-center text-white"> Made with <span class="heart">❤</span> Febin Kallungal Paul</p>
    </div>
    <!-- /.container -->
  </footer> 

  <!-- Bootstrap core JavaScript -->
  <script src="{% static '/blog/vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static '/blog/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script type="text/javascript">
      
        $(document).on('click', '#like', function(event){
          event.preventDefault();
          var pk = $(this).attr('value');
          $.ajax({
            type: 'POST',
            url: '{% url "like_post" %}',
            data: {'id':pk, 'csrfmiddlewaretoken': '{{ csrf_token }}'},
            dataType: 'json',
            success: function(response){
              $('#like-section').html(response['form'])
              console.log($('#like-section').html(response['form']));
            },
            error: function(rs, e){
              console.log(rs.responseText);
            },
          });
        });
    </script>
</body>

</html>

blog/templates/blog/create_post.html
{% extends "blog/base.html" %}
{% block content %}
      <!-- Blog Entries Column -->
      <div class="col-md-12">
        <div class="card mb-4">
          <div class="card-header">
            <b>Submit your Story </b>
          </div>
        <div class="card-body">
             <form method ="POST" enctype="multipart/form-data">
             {% csrf_token %}
            <label for="id_title"><b>Title&nbsp&nbsp</b></label>
            {{form.title}}
             <div class="card mb-4">
             <p class="m-0 text-center">Add your story below</p>
             {{form.text}}
             </div>
             <button type="submit" class ="btn btn-primary" style="float: right;"> Submit</button>
             </form>
          </div>
        </div>
      </div>
{% endblock %}

blog/templates/blog/index.html
{% extends "blog/base.html" %}
 
{% block content %}

      <!-- Blog Entries Column -->
      <div class="col-md-12">
        {% for post in blog_posts %}

        <!-- Blog Post -->
        <div class="card mb-4">
          {% comment %} {% if post.picture %}
          <img class="card-img-top" src="{{post.picture.url}}" alt="Card image cap">
          {% endif %} {% endcomment %}
          <div class="card-body">
            <br><h3 class="card-title">{{post.title}}</h3>
            <p class="card-text">{{post.text|truncatechars:100}}</p>
            <p> <b>{{ post.total_likes }} Like{{ post.total_likes|pluralize }}</b> </p>
            <a href="{% url 'blogdetail' post.pk %}" class="btn btn-primary">Read Full Story&rarr;</a>
          </div>
          <div class="card-footer text-muted">
            Posted on {{post.date}} by
            <a href="#">{{post.author}}</a>
          </div>
        </div>

        {% endfor %}

        {% if is_paginated %}
        <!-- Pagination -->
        <ul class="pagination justify-content-center mb-4">
          {% if page_obj.has_previous %}
          <li class="page-item">
            <a class="page-link" href="?page={{page_obj.previous_page_number}}">&larr; Previous Page</a>
          </li>
          {% endif %}

          {% if page_obj.has_next %}
          <li class="page-item">
            <a class="page-link" href="?page={{page_obj.next_page_number}}">Next Page &rarr;</a>
          </li>
          {% endif %}
        </ul>
        {% endif %}

      </div>      
{% endblock %}

blog/templates/blog/like_section.html
{{ post.total_likes }} Like{{ post.total_likes|pluralize }}
{% if request.user.is_authenticated %}
<form action="{% url 'like_post' %}" method="post">
  {% csrf_token %}
  {% if is_liked %}
    <button type="submit" id="like" name="post_id" value="{{ post.id }}" class="btn btn-primary" style="float: right;">Dislike</button>
  {% else %}
    <button type="submit" id="like" name="post_id" value="{{ post.id }}" class="btn btn-primary" style="float: right;">Like</button>
  {% endif %}
</form>
{% endif %}

blog/templates/blog/post_detail.html
{% extends "blog/base.html" %}

{% block content %}
      <!-- Blog Entries Column -->
      <div class="col-md-8 mt-4">
        <!-- Blog Post -->
        <div class="card mb-4">
          {% if post.picture %}
          <img class="card-img-top" src="{{post.picture.url}}" alt="Card image cap">
          {% endif %}
          <div class="card-body">
            <h3 class="card-title">{{object.title}}</h3>
            <p class="card-text">{{object.text|linebreaks}}</p>
            <div id="like-section">
          {% include 'blog/like_section.html' %}
          </div>
          </div>
          <div class="card-footer text-muted">
            Posted on {{object.date}} by
            <a href="#">{{object.author}}</a>
          </div>
        </div>
      </div>

{% endblock %}

users/templates/users/login.html
{% comment %} {% extends "blog/base.html" %}

{% block content %}
      <!-- Blog Entries Column -->
      <div class="col-md-8">
          <div class="card-header">
            Please login
          </div>
        <div class="card-body">
             <form method ="POST">
             {% csrf_token %}
             {{form.as_p}}
             <button type="submit" class ="btn btn-primary"> Login</button>
             <h5> Register to add your story .?.<a href="{% url 'register' %}"> click here.</a></h5>
             </form>
          </div>
        </div>
      </div>

{% endblock %} {% endcomment %}




<!DOCTYPE html>
<html>
    
<head>
    
	<title>Login - CovidStories </title>
	<link rel="icon" href="https://img.icons8.com/nolan/64/coronavirus.png" type="image/gif" sizes="16x16">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">


	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: #474e5d !important;
		}
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: #dee2e6;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: #fff;
			
		}

		.login_btn {
			width: 100%;
			background: #33ccff !important;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #f7ba5b !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

		#messages{
			background-color: grey;
			color: #fff;
			padding: 10px;
			margin-top: 10px;
		}
	</style>

</head>
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">


					<h3 id="form-title">LOGIN</h3>
				</div>
				<div class="d-flex justify-content-center form_container">
					<form method="POST" action="">
          {% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							<input type="text" name="username" placeholder="Username..." class="form-control">
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
								<input type="password" name="password" placeholder="Password..." class="form-control" >
						</div>

							<div class="d-flex justify-content-center mt-3 login_container">
				 				<input class="btn login_btn" type="submit" value="Login">
				   			</div>
					</form>

				</div>

        {% for messages in messages %}
        <p>{{ messages }}</P>
        {% endfor %}
		
				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Don't have an account? <a href="{% url 'register' %}" class="ml-2">Sign Up</a>
					</div>
			
				</div>
			</div>
		</div>
	</div>
</body>

</html>

users/templates/users/logout.html
{% extends "blog/base.html" %}

{% block content %}
      <!-- Blog Entries Column -->
      <div class="col-md-8 mt-4">
        <h5>You have logged out.<a href="{% url 'login' %}"> login back here.</a></h5>
        </div>

{% endblock %}

users/templates/users/register.html
<!DOCTYPE html>
<html>
    
<head>
	<title>Register - CovidStories </title>
	<link rel="icon" href="https://img.icons8.com/nolan/64/coronavirus.png" type="image/gif" sizes="16x16">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">

	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: #474e5d !important;
		}
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: #dee2e6;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: #fff;
		}
		.login_btn {
			width: 100%;
			background: #33ccff !important;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #f7ba5b !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

	</style>

</head>
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">
					<h3 id="form-title">REGISTER ACCOUNT</h3>
				</div>
				<div class="d-flex justify-content-center form_container">

					<form method="POST" action="">
          {% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							{{ form.username }}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-envelope-square"></i></span>
							</div>
							{{ form.email }}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
							{{ form.password1 }}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
							{{ form.password2 }}
						</div>
              
				   		<div class="d-flex justify-content-center mt-3 login_container">
				 			<input class="btn login_btn" type="submit" value="Register Account">
				   		</div>
					</form>
				</div>
        {{ form.errors }}
		
				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Already have an account? <a href="{% url 'login' %}" class="ml-2">Login</a>
					</div>
				</div>
			</div>
		</div>
	</div>
	<script>
						/* Because i didnt set placeholder values in forms.py they will be set here using vanilla Javascript
		//We start indexing at one because CSRF_token is considered and input field 
		 */

		//Query All input fields
		var form_fields = document.getElementsByTagName('input')
		form_fields[1].placeholder='Username..';
		form_fields[2].placeholder='Email..';
		form_fields[3].placeholder='Enter password...';
		form_fields[4].placeholder='Re-enter Password...';


		for (var field in form_fields){	
			form_fields[field].className += ' form-control'
		}
	</script>
</body>
</html>